import {
  ComplianceCategory as C,
  ComplianceModuleEntry,
  ModuleStatus as S,
  RegulatoryBody as R,
} from './compliance-registry.types';

export const COMPLIANCE_MODULES: ComplianceModuleEntry[] = [
  // ═══════════════════════════════════════════════════════════════
  // INTEREST RATE RISK (M-01 through M-10)
  // ═══════════════════════════════════════════════════════════════
  {
    moduleId: 'M-01',
    name: 'Duration Gap Analysis',
    nameEs: 'Análisis de Brecha de Duración',
    category: C.INTEREST_RATE_RISK,
    description:
      'Macaulay/modified duration gap between assets and liabilities',
    descriptionEs:
      'Brecha de duración Macaulay/modificada entre activos y pasivos',
    serviceFile: 'alm/duration.service.ts',
    entryFunction: 'calculateDurationGap',
    requiredInputs: ['balanceSheetItems', 'yieldCurve'],
    outputFields: [
      'durationGap',
      'assetDuration',
      'liabilityDuration',
      'modifiedDuration',
    ],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §4.2' },
      { body: R.NCUA, citation: 'NCUA Letter 12-CU-11' },
    ],
    thresholds: [
      {
        metric: 'durationGap',
        pass: '< 3.0 years',
        warn: '3.0–4.5 years',
        fail: '> 4.5 years',
        unit: 'years',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-duration-gap',
    dependsOn: [],
  },
  {
    moduleId: 'M-02',
    name: 'NII Sensitivity',
    nameEs: 'Sensibilidad de Ingreso Neto por Intereses',
    category: C.INTEREST_RATE_RISK,
    description:
      'Net Interest Income sensitivity to parallel rate shocks (±100-400bp)',
    descriptionEs:
      'Sensibilidad del NII a choques paralelos de tasas (±100-400pb)',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateNIISensitivity',
    requiredInputs: ['balanceSheetItems', 'repricingGaps'],
    outputFields: [
      'niiChange',
      'niiChangePercent',
      'rateShockBp',
      'rsaTotal',
      'rslTotal',
    ],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §4.3' },
      { body: R.FRB, citation: 'SR 10-1 §III.B' },
    ],
    thresholds: [
      {
        metric: 'niiChangePercent',
        pass: '< 20%',
        warn: '20–35%',
        fail: '> 35%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-nii-sensitivity',
    dependsOn: ['M-01'],
  },
  {
    moduleId: 'M-03',
    name: 'Economic Value of Equity (EVE)',
    nameEs: 'Valor Económico del Patrimonio',
    category: C.INTEREST_RATE_RISK,
    description: 'PV(Assets) - PV(Liabilities) across rate scenarios',
    descriptionEs: 'VP(Activos) - VP(Pasivos) bajo escenarios de tasas',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateEVESensitivity',
    requiredInputs: ['balanceSheetItems', 'yieldCurve', 'rateScenarios'],
    outputFields: ['eve', 'eveChange', 'eveChangePercent'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §4.4' },
      { body: R.FRB, citation: 'SR 10-1 §III.C' },
    ],
    thresholds: [
      {
        metric: 'eveChangePercent',
        pass: '> -20%',
        warn: '-20% to -30%',
        fail: '< -30%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-eve-sensitivity',
    dependsOn: ['M-01'],
  },
  {
    moduleId: 'M-04',
    name: 'Repricing Gap Analysis',
    nameEs: 'Análisis de Brecha de Reprecio',
    category: C.INTEREST_RATE_RISK,
    description: 'RSA vs RSL by time bucket for static gap and cumulative gap',
    descriptionEs:
      'ASR vs PSR por banda temporal para brecha estática y acumulada',
    serviceFile: 'alm/repricing-gap.service.ts',
    entryFunction: 'calculateRepricingGap',
    requiredInputs: ['balanceSheetItems'],
    outputFields: ['buckets', 'cumulativeGap', 'gapRatio'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §4.1' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-repricing-gap',
    dependsOn: [],
  },
  {
    moduleId: 'M-05',
    name: 'Convexity Analysis',
    nameEs: 'Análisis de Convexidad',
    category: C.INTEREST_RATE_RISK,
    description: 'Second-order rate sensitivity for non-linear bond portfolios',
    descriptionEs:
      'Sensibilidad de segundo orden para carteras de bonos no lineales',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateConvexity',
    requiredInputs: ['balanceSheetItems', 'yieldCurve'],
    outputFields: ['convexity', 'effectiveDuration', 'priceChangeEstimate'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §4.5' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-convexity',
    dependsOn: ['M-01'],
  },
  {
    moduleId: 'M-06',
    name: 'Deposit Beta Estimation',
    nameEs: 'Estimación de Beta de Depósitos',
    category: C.INTEREST_RATE_RISK,
    description: 'Deposit rate pass-through relative to market rate changes',
    descriptionEs:
      'Traspaso de tasas de depósitos relativo a cambios en tasas de mercado',
    serviceFile: 'alm/deposit-beta.service.ts',
    entryFunction: 'estimateDepositBeta',
    requiredInputs: ['depositTiers', 'marketRateHistory'],
    outputFields: ['beta', 'rSquared', 'lagMonths', 'coreDepositRatio'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §4.6' },
    ],
    thresholds: [
      {
        metric: 'beta',
        pass: '< 0.6',
        warn: '0.6–0.8',
        fail: '> 0.8',
        unit: 'ratio',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-deposit-beta',
    dependsOn: [],
  },
  {
    moduleId: 'M-07',
    name: 'Key Rate Duration',
    nameEs: 'Duración por Tasa Clave',
    category: C.INTEREST_RATE_RISK,
    description:
      'Sensitivity to individual key-rate shifts along the yield curve',
    descriptionEs:
      'Sensibilidad a movimientos individuales en puntos clave de la curva',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateKeyRateDurations',
    requiredInputs: ['balanceSheetItems', 'yieldCurve'],
    outputFields: ['keyRateDurations', 'tenorPoints'],
    regulatoryReferences: [{ body: R.FRB, citation: 'SR 10-1 §III.D' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-key-rate-duration',
    dependsOn: ['M-01', 'M-03'],
  },
  {
    moduleId: 'M-08',
    name: 'PCA Yield Curve Model',
    nameEs: 'Modelo PCA de Curva de Rendimiento',
    category: C.INTEREST_RATE_RISK,
    description:
      '3-factor PCA (level, slope, curvature) for yield curve dynamics',
    descriptionEs:
      'PCA de 3 factores (nivel, pendiente, curvatura) para dinámica de curva',
    serviceFile: 'alm/yield-curve.service.ts',
    entryFunction: 'fitPCAModel',
    requiredInputs: ['historicalYieldCurves'],
    outputFields: ['factors', 'eigenvalues', 'varianceExplained', 'loadings'],
    regulatoryReferences: [{ body: R.FRB, citation: 'SR 10-1 §IV.A' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-pca-yield-curve',
    dependsOn: [],
  },
  {
    moduleId: 'M-09',
    name: 'Funds Transfer Pricing (FTP)',
    nameEs: 'Precio de Transferencia de Fondos',
    category: C.INTEREST_RATE_RISK,
    description:
      'Internal FTP rates for profitability analysis by product line',
    descriptionEs:
      'Tasas FTP internas para análisis de rentabilidad por línea de producto',
    serviceFile: 'alm/ftp.service.ts',
    entryFunction: 'calculateFTP',
    requiredInputs: ['balanceSheetItems', 'yieldCurve', 'liquidityPremiums'],
    outputFields: ['ftpRates', 'marginContribution', 'spreadByProduct'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §5.1' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-ftp',
    dependsOn: ['M-01', 'M-08'],
  },
  {
    moduleId: 'M-10',
    name: 'IRR Policy Limits',
    nameEs: 'Límites de Política de Riesgo de Tasa',
    category: C.INTEREST_RATE_RISK,
    description:
      'Board-approved IRR policy limit monitoring and breach detection',
    descriptionEs:
      'Monitoreo de límites de política IRR aprobados por junta y detección de brechas',
    serviceFile: 'alm/irr-policy.service.ts',
    entryFunction: 'checkPolicyLimits',
    requiredInputs: ['irrPolicyLimits', 'currentMetrics'],
    outputFields: ['breaches', 'nearBreaches', 'complianceStatus'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §6' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-irr-policy-limits',
    dependsOn: ['M-01', 'M-02', 'M-03'],
  },

  // ═══════════════════════════════════════════════════════════════
  // LIQUIDITY (M-11 through M-20)
  // ═══════════════════════════════════════════════════════════════
  {
    moduleId: 'M-11',
    name: 'Liquidity Coverage Ratio (LCR)',
    nameEs: 'Razón de Cobertura de Liquidez',
    category: C.LIQUIDITY,
    description: 'HQLA / Net Cash Outflows (30-day stress)',
    descriptionEs: 'HQLA / Salidas Netas de Efectivo (estrés 30 días)',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateLCR',
    requiredInputs: ['liquidityPosition'],
    outputFields: ['lcr', 'hqla', 'netCashOutflows', 'status'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §3.1' },
      { body: R.FRB, citation: 'Regulation YY §249' },
    ],
    thresholds: [
      {
        metric: 'lcr',
        pass: '≥ 100%',
        warn: '90–100%',
        fail: '< 90%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-lcr',
    dependsOn: [],
  },
  {
    moduleId: 'M-12',
    name: 'Net Stable Funding Ratio (NSFR)',
    nameEs: 'Razón de Financiamiento Estable Neto',
    category: C.LIQUIDITY,
    description: 'Available stable funding / Required stable funding',
    descriptionEs:
      'Financiamiento estable disponible / Financiamiento estable requerido',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateNSFR',
    requiredInputs: ['balanceSheetItems', 'liquidityPosition'],
    outputFields: ['nsfr', 'availableStableFunding', 'requiredStableFunding'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §3.2' },
    ],
    thresholds: [
      {
        metric: 'nsfr',
        pass: '≥ 100%',
        warn: '90–100%',
        fail: '< 90%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-nsfr',
    dependsOn: ['M-11'],
  },
  {
    moduleId: 'M-13',
    name: 'Cash Flow Projections',
    nameEs: 'Proyecciones de Flujo de Efectivo',
    category: C.LIQUIDITY,
    description:
      'Contractual and behavioral cash flow projections over 12 months',
    descriptionEs:
      'Proyecciones de flujo de efectivo contractual y conductual a 12 meses',
    serviceFile: 'alm/liquidity-advanced.service.ts',
    entryFunction: 'projectCashFlows',
    requiredInputs: ['balanceSheetItems', 'repaymentSchedules'],
    outputFields: ['monthlyProjections', 'cumulativeGap', 'fundingNeeds'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §3.3' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-cash-flow-projection',
    dependsOn: [],
  },
  {
    moduleId: 'M-14',
    name: 'Liquidity Stress Testing',
    nameEs: 'Prueba de Estrés de Liquidez',
    category: C.LIQUIDITY,
    description:
      'Idiosyncratic, market-wide, and combined liquidity stress scenarios',
    descriptionEs:
      'Escenarios de estrés de liquidez idiosincrásico, sistémico y combinado',
    serviceFile: 'alm/stress-testing/stress-testing.service.ts',
    entryFunction: 'runLiquidityStress',
    requiredInputs: ['liquidityPosition', 'stressScenarios'],
    outputFields: ['scenarioResults', 'survivalDays', 'contingencyGap'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §3.4' },
      { body: R.FRB, citation: 'SR 10-6' },
    ],
    thresholds: [
      {
        metric: 'survivalDays',
        pass: '≥ 30 days',
        warn: '15–30 days',
        fail: '< 15 days',
        unit: 'days',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-liquidity-stress',
    dependsOn: ['M-11', 'M-13'],
  },
  {
    moduleId: 'M-15',
    name: 'Contingency Funding Plan',
    nameEs: 'Plan de Contingencia de Financiamiento',
    category: C.LIQUIDITY,
    description: 'Available contingent funding sources and trigger events',
    descriptionEs:
      'Fuentes de financiamiento contingente disponibles y eventos de activación',
    serviceFile: 'alm/liquidity-advanced.service.ts',
    entryFunction: 'assessContingencyFunding',
    requiredInputs: [
      'liquidityPosition',
      'creditFacilities',
      'pledgeableAssets',
    ],
    outputFields: ['availableSources', 'totalCapacity', 'triggerMatrix'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §3.5' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-contingency-funding',
    dependsOn: ['M-14'],
  },
  {
    moduleId: 'M-16',
    name: 'Deposit Concentration Analysis',
    nameEs: 'Análisis de Concentración de Depósitos',
    category: C.LIQUIDITY,
    description: 'Large depositor dependency and concentration risk metrics',
    descriptionEs:
      'Dependencia de grandes depositantes y métricas de riesgo de concentración',
    serviceFile: 'alm/concentration.service.ts',
    entryFunction: 'analyzeDepositConcentration',
    requiredInputs: ['depositTiers', 'balanceSheetItems'],
    outputFields: ['herfindahlIndex', 'top10Ratio', 'concentrationRisk'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §3.6' },
    ],
    thresholds: [
      {
        metric: 'top10Ratio',
        pass: '< 25%',
        warn: '25–40%',
        fail: '> 40%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-deposit-concentration',
    dependsOn: [],
  },
  {
    moduleId: 'M-17',
    name: 'Core vs Non-Core Funding',
    nameEs: 'Financiamiento Base vs No Base',
    category: C.LIQUIDITY,
    description: 'Classification and stability analysis of funding sources',
    descriptionEs:
      'Clasificación y análisis de estabilidad de fuentes de financiamiento',
    serviceFile: 'alm/liquidity-advanced.service.ts',
    entryFunction: 'classifyFunding',
    requiredInputs: ['depositTiers', 'borrowings'],
    outputFields: ['coreFundingRatio', 'volatileFundingRatio', 'fundingMix'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §3.7' },
    ],
    thresholds: [
      {
        metric: 'coreFundingRatio',
        pass: '≥ 70%',
        warn: '60–70%',
        fail: '< 60%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-core-funding',
    dependsOn: ['M-16'],
  },
  {
    moduleId: 'M-18',
    name: 'Encumbered Asset Analysis',
    nameEs: 'Análisis de Activos Gravados',
    category: C.LIQUIDITY,
    description: 'Pledged/encumbered assets vs unencumbered HQLA availability',
    descriptionEs: 'Activos pignorados vs disponibilidad de HQLA no gravados',
    serviceFile: 'alm/liquidity-advanced.service.ts',
    entryFunction: 'analyzeEncumberedAssets',
    requiredInputs: ['balanceSheetItems', 'pledgedAssets'],
    outputFields: ['encumbranceRatio', 'freeAssets', 'pledgedTotal'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §3.8' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-encumbered-assets',
    dependsOn: [],
  },
  {
    moduleId: 'M-19',
    name: 'Intraday Liquidity Monitoring',
    nameEs: 'Monitoreo de Liquidez Intradía',
    category: C.LIQUIDITY,
    description: 'Real-time liquidity position tracking and alert thresholds',
    descriptionEs:
      'Seguimiento de posición de liquidez en tiempo real y umbrales de alerta',
    serviceFile: 'alm/realtime-alm/market-data-feed.service.ts',
    entryFunction: 'getIntradayPosition',
    requiredInputs: ['currentPosition', 'scheduledFlows'],
    outputFields: ['currentLiquidity', 'peakUsage', 'minimumBalance', 'alerts'],
    regulatoryReferences: [{ body: R.FRB, citation: 'SR 10-6 §IV' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-intraday-liquidity',
    dependsOn: ['M-11'],
  },
  {
    moduleId: 'M-20',
    name: 'Early Warning System (Liquidity)',
    nameEs: 'Sistema de Alerta Temprana (Liquidez)',
    category: C.LIQUIDITY,
    description: 'Leading indicators for liquidity deterioration',
    descriptionEs: 'Indicadores adelantados de deterioro de liquidez',
    serviceFile: 'alm/asset-ews.service.ts',
    entryFunction: 'runEarlyWarningSystem',
    requiredInputs: ['liquidityPosition', 'trendData'],
    outputFields: ['signals', 'overallAlert', 'trendDirection'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §7.1' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-asset-ews',
    dependsOn: ['M-11', 'M-14'],
  },

  // ═══════════════════════════════════════════════════════════════
  // CAPITAL ADEQUACY (M-21 through M-28)
  // ═══════════════════════════════════════════════════════════════
  {
    moduleId: 'M-21',
    name: 'Net Worth Ratio',
    nameEs: 'Razón de Patrimonio Neto',
    category: C.CAPITAL_ADEQUACY,
    description: 'Net worth / Total assets — primary COSSEC capital metric',
    descriptionEs:
      'Patrimonio neto / Activos totales — métrica primaria de capital COSSEC',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateNetWorthRatio',
    requiredInputs: ['balanceSheetItems'],
    outputFields: ['netWorthRatio', 'netWorth', 'totalAssets'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Ley 255-2002 Art. 14.01' },
    ],
    thresholds: [
      {
        metric: 'netWorthRatio',
        pass: '≥ 10%',
        warn: '7–10%',
        fail: '< 7%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-net-worth-ratio',
    dependsOn: [],
  },
  {
    moduleId: 'M-22',
    name: 'Capital Adequacy Ratio',
    nameEs: 'Razón de Adecuación de Capital',
    category: C.CAPITAL_ADEQUACY,
    description: 'Risk-weighted capital adequacy per COSSEC requirements',
    descriptionEs:
      'Adecuación de capital ponderada por riesgo según requisitos COSSEC',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateCapitalAdequacy',
    requiredInputs: ['balanceSheetItems', 'riskWeights'],
    outputFields: ['capitalRatio', 'tier1Capital', 'riskWeightedAssets'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Ley 255-2002 Art. 14.02' },
      { body: R.NCUA, citation: 'NCUA Part 702' },
    ],
    thresholds: [
      {
        metric: 'capitalRatio',
        pass: '≥ 7%',
        warn: '5–7%',
        fail: '< 5%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-capital-adequacy',
    dependsOn: [],
  },
  {
    moduleId: 'M-23',
    name: 'NCUA Risk-Based Capital (RBC2)',
    nameEs: 'Capital Basado en Riesgo NCUA',
    category: C.CAPITAL_ADEQUACY,
    description: 'NCUA Part 702 risk-based capital calculation for complex CUs',
    descriptionEs:
      'Cálculo de capital basado en riesgo NCUA Parte 702 para CUs complejas',
    serviceFile: 'alm/ncua-rbc2.service.ts',
    entryFunction: 'calculateRBC2',
    requiredInputs: ['balanceSheetItems', 'offBalanceSheetItems'],
    outputFields: [
      'rbc2Ratio',
      'totalRiskWeightedAssets',
      'netWorth',
      'classification',
    ],
    regulatoryReferences: [
      { body: R.NCUA, citation: 'NCUA Part 702 Subpart D' },
    ],
    thresholds: [
      {
        metric: 'rbc2Ratio',
        pass: '≥ 10%',
        warn: '8–10%',
        fail: '< 8%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-ncua-rbc2',
    dependsOn: [],
  },
  {
    moduleId: 'M-24',
    name: 'Capital Planning & Projections',
    nameEs: 'Planificación y Proyecciones de Capital',
    category: C.CAPITAL_ADEQUACY,
    description:
      'Forward-looking capital adequacy under normal and stress conditions',
    descriptionEs:
      'Adecuación de capital prospectiva bajo condiciones normales y de estrés',
    serviceFile: 'alm/swarm/capital-adequacy-adapter.service.ts',
    entryFunction: 'projectCapital',
    requiredInputs: [
      'balanceSheetItems',
      'growthAssumptions',
      'stressScenarios',
    ],
    outputFields: ['baselineProjection', 'stressProjection', 'capitalBuffer'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §5.2' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-capital-planning',
    dependsOn: ['M-21', 'M-22'],
  },
  {
    moduleId: 'M-25',
    name: 'Leverage Ratio',
    nameEs: 'Razón de Apalancamiento',
    category: C.CAPITAL_ADEQUACY,
    description: 'Tier 1 capital / Total exposure (on + off balance sheet)',
    descriptionEs:
      'Capital Tier 1 / Exposición total (dentro y fuera de balance)',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateLeverageRatio',
    requiredInputs: ['balanceSheetItems'],
    outputFields: ['leverageRatio', 'tier1Capital', 'totalExposure'],
    regulatoryReferences: [{ body: R.FRB, citation: 'Regulation Q §217' }],
    thresholds: [
      {
        metric: 'leverageRatio',
        pass: '≥ 5%',
        warn: '4–5%',
        fail: '< 4%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-leverage-ratio',
    dependsOn: [],
  },
  {
    moduleId: 'M-26',
    name: 'Dividend Capacity Analysis',
    nameEs: 'Análisis de Capacidad de Dividendos',
    category: C.CAPITAL_ADEQUACY,
    description: 'Maximum sustainable dividend given capital constraints',
    descriptionEs:
      'Dividendo máximo sostenible dadas las restricciones de capital',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'analyzeDividendCapacity',
    requiredInputs: ['balanceSheetItems', 'earnings', 'capitalTargets'],
    outputFields: ['maxDividend', 'retentionNeeded', 'capitalImpact'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Ley 255-2002 Art. 14.03' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-dividend-capacity',
    dependsOn: ['M-21'],
  },
  {
    moduleId: 'M-27',
    name: 'Capital Stress Testing',
    nameEs: 'Prueba de Estrés de Capital',
    category: C.CAPITAL_ADEQUACY,
    description:
      'Capital adequacy under adverse and severely adverse scenarios',
    descriptionEs:
      'Adecuación de capital bajo escenarios adversos y severamente adversos',
    serviceFile: 'alm/stress-testing/stress-testing.service.ts',
    entryFunction: 'runCapitalStress',
    requiredInputs: ['balanceSheetItems', 'stressScenarios', 'capitalMetrics'],
    outputFields: ['scenarioCapitalRatios', 'breachPoints', 'recoveryTimeline'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §5.3' },
      { body: R.FRB, citation: 'SR 12-7' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-capital-stress',
    dependsOn: ['M-21', 'M-22', 'M-14'],
  },
  {
    moduleId: 'M-28',
    name: 'Return on Assets (ROA)',
    nameEs: 'Rendimiento sobre Activos',
    category: C.CAPITAL_ADEQUACY,
    description: 'Net income / Average total assets — profitability indicator',
    descriptionEs:
      'Ingreso neto / Promedio de activos totales — indicador de rentabilidad',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateROA',
    requiredInputs: ['incomeStatement', 'balanceSheetItems'],
    outputFields: ['roa', 'netIncome', 'averageAssets'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §6.1' },
    ],
    thresholds: [
      {
        metric: 'roa',
        pass: '≥ 0.75%',
        warn: '0.5–0.75%',
        fail: '< 0.5%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-roa',
    dependsOn: [],
  },

  // ═══════════════════════════════════════════════════════════════
  // CREDIT RISK (M-29 through M-38)
  // ═══════════════════════════════════════════════════════════════
  {
    moduleId: 'M-29',
    name: 'CECL Provisioning (WARM)',
    nameEs: 'Provisión CECL (WARM)',
    category: C.CREDIT_RISK,
    description:
      'Weighted Average Remaining Maturity method for expected credit losses',
    descriptionEs:
      'Método de Madurez Promedio Ponderada Restante para pérdidas crediticias esperadas',
    serviceFile: 'alm/cecl.service.ts',
    entryFunction: 'calculateCECL_WARM',
    requiredInputs: ['loanSegments', 'historicalLossRates'],
    outputFields: ['allowance', 'coverageRatio', 'segmentBreakdown'],
    regulatoryReferences: [
      { body: R.FASB, citation: 'ASC 326-20' },
      { body: R.NCUA, citation: 'NCUA Letter 16-CU-13' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-cecl-warm',
    dependsOn: [],
  },
  {
    moduleId: 'M-30',
    name: 'CECL Provisioning (Vintage)',
    nameEs: 'Provisión CECL (Añada)',
    category: C.CREDIT_RISK,
    description: 'Vintage cohort analysis for expected credit losses',
    descriptionEs:
      'Análisis de cohorte por añada para pérdidas crediticias esperadas',
    serviceFile: 'alm/cecl.service.ts',
    entryFunction: 'calculateCECL_Vintage',
    requiredInputs: ['loanCohorts', 'historicalLossRates'],
    outputFields: ['allowance', 'vintageMatrix', 'lossTimeline'],
    regulatoryReferences: [{ body: R.FASB, citation: 'ASC 326-20' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-cecl-vintage',
    dependsOn: [],
  },
  {
    moduleId: 'M-31',
    name: 'CECL Provisioning (PD×LGD)',
    nameEs: 'Provisión CECL (PD×LGD)',
    category: C.CREDIT_RISK,
    description: 'Probability of Default × Loss Given Default model',
    descriptionEs:
      'Modelo de Probabilidad de Incumplimiento × Pérdida Dado el Incumplimiento',
    serviceFile: 'alm/cecl.service.ts',
    entryFunction: 'calculateCECL_PDLGD',
    requiredInputs: ['loanSegments', 'pdCurves', 'lgdEstimates'],
    outputFields: ['allowance', 'expectedLoss', 'pdBySegment', 'lgdBySegment'],
    regulatoryReferences: [{ body: R.FASB, citation: 'ASC 326-20' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-cecl-pdlgd',
    dependsOn: [],
  },
  {
    moduleId: 'M-32',
    name: 'Loan Concentration Analysis',
    nameEs: 'Análisis de Concentración de Préstamos',
    category: C.CREDIT_RISK,
    description:
      'Loan portfolio concentration by type, geography, and borrower',
    descriptionEs:
      'Concentración de cartera de préstamos por tipo, geografía y prestatario',
    serviceFile: 'alm/concentration.service.ts',
    entryFunction: 'analyzeLoanConcentration',
    requiredInputs: ['loanSegments', 'concentrationLimits'],
    outputFields: ['concentrationByType', 'herfindahlIndex', 'limitBreaches'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §2.3' },
      { body: R.NCUA, citation: 'NCUA Part 723' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-loan-concentration',
    dependsOn: [],
  },
  {
    moduleId: 'M-33',
    name: 'Delinquency Analysis',
    nameEs: 'Análisis de Morosidad',
    category: C.CREDIT_RISK,
    description: 'Delinquency rates by aging bucket and loan type',
    descriptionEs: 'Tasas de morosidad por envejecimiento y tipo de préstamo',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'analyzeDelinquency',
    requiredInputs: ['loanSegments'],
    outputFields: ['delinquencyRate', 'agingBuckets', 'nplRatio'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §2.4' },
    ],
    thresholds: [
      {
        metric: 'nplRatio',
        pass: '< 3%',
        warn: '3–5%',
        fail: '> 5%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-delinquency',
    dependsOn: [],
  },
  {
    moduleId: 'M-34',
    name: 'KMV-Merton Default Probability',
    nameEs: 'Probabilidad de Incumplimiento KMV-Merton',
    category: C.CREDIT_RISK,
    description: 'Structural credit risk model using balance sheet equity/debt',
    descriptionEs:
      'Modelo estructural de riesgo crediticio usando patrimonio/deuda del balance',
    serviceFile: 'alm/kmv-merton.service.ts',
    entryFunction: 'calculateKMV',
    requiredInputs: ['balanceSheetItems', 'institution'],
    outputFields: ['distanceToDefault', 'defaultProbability', 'expectedLoss'],
    regulatoryReferences: [{ body: R.FRB, citation: 'SR 11-7 §III' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-kmv-merton',
    dependsOn: [],
  },
  {
    moduleId: 'M-35',
    name: 'Credit Migration Matrix',
    nameEs: 'Matriz de Migración Crediticia',
    category: C.CREDIT_RISK,
    description: 'Transition probabilities between credit quality grades',
    descriptionEs:
      'Probabilidades de transición entre grados de calidad crediticia',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateCreditMigration',
    requiredInputs: ['loanSegments', 'historicalRatings'],
    outputFields: ['transitionMatrix', 'downgradeRate', 'upgradeRate'],
    regulatoryReferences: [{ body: R.FRB, citation: 'SR 11-7 §IV' }],
    thresholds: [],
    status: S.IN_PROGRESS,
    modelRegistryKey: 'alm-credit-migration',
    dependsOn: ['M-34'],
  },
  {
    moduleId: 'M-36',
    name: 'Net Charge-Off Analysis',
    nameEs: 'Análisis de Cancelaciones Netas',
    category: C.CREDIT_RISK,
    description: 'Net charge-offs as percentage of average loans',
    descriptionEs:
      'Cancelaciones netas como porcentaje del promedio de préstamos',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateNetChargeOffs',
    requiredInputs: ['chargeOffData', 'loanSegments'],
    outputFields: ['ncoRatio', 'grossChargeOffs', 'recoveries'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §2.5' },
    ],
    thresholds: [
      {
        metric: 'ncoRatio',
        pass: '< 1%',
        warn: '1–2%',
        fail: '> 2%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-net-charge-offs',
    dependsOn: [],
  },
  {
    moduleId: 'M-37',
    name: 'Commercial Real Estate (CRE) Concentration',
    nameEs: 'Concentración de Bienes Raíces Comerciales',
    category: C.CREDIT_RISK,
    description: 'CRE lending concentration relative to capital',
    descriptionEs: 'Concentración de préstamos CRE relativo al capital',
    serviceFile: 'alm/concentration.service.ts',
    entryFunction: 'analyzeCREConcentration',
    requiredInputs: ['loanSegments', 'capitalMetrics'],
    outputFields: [
      'creToCapitalRatio',
      'constructionToCapitalRatio',
      'concentrationFlag',
    ],
    regulatoryReferences: [
      { body: R.NCUA, citation: 'NCUA Letter 09-CU-22' },
      { body: R.FDIC, citation: 'IL 03-2006' },
    ],
    thresholds: [
      {
        metric: 'creToCapitalRatio',
        pass: '< 300%',
        warn: '300–500%',
        fail: '> 500%',
        unit: '%',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-cre-concentration',
    dependsOn: ['M-32'],
  },
  {
    moduleId: 'M-38',
    name: 'Troubled Debt Restructuring (TDR)',
    nameEs: 'Reestructuración de Deuda Problemática',
    category: C.CREDIT_RISK,
    description:
      'Identification and measurement of troubled debt restructurings',
    descriptionEs:
      'Identificación y medición de reestructuraciones de deuda problemática',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'analyzeTDR',
    requiredInputs: ['loanSegments', 'modificationHistory'],
    outputFields: ['tdrBalance', 'tdrToLoans', 'redefaultRate'],
    regulatoryReferences: [{ body: R.FASB, citation: 'ASC 310-40' }],
    thresholds: [],
    status: S.IN_PROGRESS,
    modelRegistryKey: 'alm-tdr',
    dependsOn: [],
  },

  // ═══════════════════════════════════════════════════════════════
  // STRESS TESTING (M-39 through M-44)
  // ═══════════════════════════════════════════════════════════════
  {
    moduleId: 'M-39',
    name: 'Regulatory Stress Scenarios',
    nameEs: 'Escenarios de Estrés Regulatorio',
    category: C.STRESS_TESTING,
    description: 'COSSEC baseline + adverse + severely adverse scenarios',
    descriptionEs: 'Escenarios COSSEC base + adverso + severamente adverso',
    serviceFile: 'alm/stress-testing/stress-testing.service.ts',
    entryFunction: 'runRegulatoryStress',
    requiredInputs: [
      'balanceSheetItems',
      'liquidityPosition',
      'cossecCompliance',
    ],
    outputFields: ['scenarioResults', 'overallRating', 'impactMatrix'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §7.2' },
      { body: R.FRB, citation: 'SR 12-7' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-regulatory-stress',
    dependsOn: ['M-11', 'M-21'],
  },
  {
    moduleId: 'M-40',
    name: 'Custom Scenario Builder',
    nameEs: 'Constructor de Escenarios Personalizados',
    category: C.STRESS_TESTING,
    description: 'User-defined stress scenarios with multi-factor shocks',
    descriptionEs:
      'Escenarios de estrés definidos por usuario con choques multifactor',
    serviceFile: 'alm/custom-scenario.service.ts',
    entryFunction: 'runCustomScenario',
    requiredInputs: [
      'scenarioParameters',
      'balanceSheetItems',
      'currentMetrics',
    ],
    outputFields: ['impactSummary', 'metricDeltas', 'breachFlags'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §7.3' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-custom-scenario',
    dependsOn: ['M-39'],
  },
  {
    moduleId: 'M-41',
    name: 'Monte Carlo Simulation',
    nameEs: 'Simulación Monte Carlo',
    category: C.STRESS_TESTING,
    description: 'Vasicek rate model, 10K paths, 95th percentile VaR',
    descriptionEs:
      'Modelo de tasas Vasicek, 10K trayectorias, VaR percentil 95',
    serviceFile: 'alm/hjm-worker.ts',
    entryFunction: 'runMonteCarloSimulation',
    requiredInputs: ['currentRates', 'volatilityParams', 'correlationMatrix'],
    outputFields: ['pathResults', 'var95', 'var99', 'expectedShortfall'],
    regulatoryReferences: [{ body: R.FRB, citation: 'SR 11-7 §V' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-monte-carlo',
    dependsOn: ['M-08'],
  },
  {
    moduleId: 'M-42',
    name: 'Reverse Stress Testing',
    nameEs: 'Prueba de Estrés Inversa',
    category: C.STRESS_TESTING,
    description:
      'Identifies scenarios that would breach capital/liquidity limits',
    descriptionEs:
      'Identifica escenarios que violarían límites de capital/liquidez',
    serviceFile: 'alm/stress-testing/stress-testing.service.ts',
    entryFunction: 'runReverseStress',
    requiredInputs: ['currentMetrics', 'policyLimits'],
    outputFields: ['breakPoints', 'criticalScenarios', 'bufferAnalysis'],
    regulatoryReferences: [{ body: R.FRB, citation: 'SR 12-7 §V' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-reverse-stress',
    dependsOn: ['M-39', 'M-41'],
  },
  {
    moduleId: 'M-43',
    name: 'Climate Risk / TCFD',
    nameEs: 'Riesgo Climático / TCFD',
    category: C.STRESS_TESTING,
    description:
      'TCFD-aligned climate scenario analysis (transition + physical risk)',
    descriptionEs:
      'Análisis de escenarios climáticos alineados a TCFD (riesgo de transición + físico)',
    serviceFile: 'alm/stress-testing/stress-testing.service.ts',
    entryFunction: 'runClimateStress',
    requiredInputs: ['portfolioExposures', 'climateScenarios'],
    outputFields: [
      'physicalRiskImpact',
      'transitionRiskImpact',
      'portfolioHeatmap',
    ],
    regulatoryReferences: [
      { body: R.FRB, citation: 'SR 22-6 (Climate Guidance)' },
    ],
    thresholds: [],
    status: S.PLANNED,
    modelRegistryKey: 'alm-climate-risk',
    dependsOn: ['M-39'],
  },
  {
    moduleId: 'M-44',
    name: 'Hurricane / Natural Disaster Scenario',
    nameEs: 'Escenario de Huracán / Desastre Natural',
    category: C.STRESS_TESTING,
    description:
      'PR-specific Cat 4/5 hurricane impact on loan portfolio and operations',
    descriptionEs:
      'Impacto de huracán Cat 4/5 específico de PR en cartera de préstamos y operaciones',
    serviceFile: 'alm/stress-testing/stress-testing.service.ts',
    entryFunction: 'runHurricaneScenario',
    requiredInputs: [
      'portfolioExposures',
      'geographicConcentration',
      'insuranceCoverage',
    ],
    outputFields: ['estimatedLosses', 'operationalImpact', 'recoveryTimeline'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2020-03 (Post-María)' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-hurricane-scenario',
    dependsOn: ['M-39'],
  },

  // ═══════════════════════════════════════════════════════════════
  // REGULATORY REPORTING (M-45 through M-52)
  // ═══════════════════════════════════════════════════════════════
  {
    moduleId: 'M-45',
    name: 'COSSEC 12-Ratio Compliance Engine',
    nameEs: 'Motor de Cumplimiento COSSEC 12 Razones',
    category: C.REGULATORY_REPORTING,
    description: 'Full COSSEC compliance scoring across all 12 required ratios',
    descriptionEs:
      'Puntuación completa de cumplimiento COSSEC en las 12 razones requeridas',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'getCOSSECCompliance',
    requiredInputs: ['balanceSheetItems'],
    outputFields: ['overallStatus', 'ratios', 'findings', 'recommendations'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Ley 255-2002 Art. 14' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-cossec-compliance',
    dependsOn: ['M-21', 'M-22', 'M-11'],
  },
  {
    moduleId: 'M-46',
    name: 'NCUA Form 5300 Generation',
    nameEs: 'Generación de Formulario NCUA 5300',
    category: C.REGULATORY_REPORTING,
    description:
      'Quarterly call report generation for NCUA-regulated credit unions',
    descriptionEs:
      'Generación de informe trimestral de llamada para CUs reguladas por NCUA',
    serviceFile: 'alm/ncua-5300.service.ts',
    entryFunction: 'generateForm5300',
    requiredInputs: ['balanceSheetItems', 'incomeStatement'],
    outputFields: ['formData', 'editChecks', 'overallStatus'],
    regulatoryReferences: [{ body: R.NCUA, citation: 'NCUA Part 741.6' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-ncua-5300',
    dependsOn: [],
  },
  {
    moduleId: 'M-47',
    name: 'Board Report Generator',
    nameEs: 'Generador de Informe de Junta',
    category: C.REGULATORY_REPORTING,
    description:
      'Quarterly board-ready PDF with KPIs, risks, and recommendations',
    descriptionEs:
      'PDF trimestral listo para junta con KPIs, riesgos y recomendaciones',
    serviceFile: 'alm/board-report.service.ts',
    entryFunction: 'generateBoardReport',
    requiredInputs: ['almSummary', 'camelScore'],
    outputFields: ['pdf', 'kpis', 'topRisks', 'recommendations'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §8' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-board-report',
    dependsOn: ['M-45', 'M-55'],
  },
  {
    moduleId: 'M-48',
    name: 'ALCO Dashboard',
    nameEs: 'Tablero ALCO',
    category: C.REGULATORY_REPORTING,
    description: 'Asset-Liability Committee dashboard with all key metrics',
    descriptionEs: 'Tablero del Comité de Activos y Pasivos con métricas clave',
    serviceFile: 'alm/alco-dashboard.service.ts',
    entryFunction: 'generateALCODashboard',
    requiredInputs: ['almSummary', 'cossecCompliance', 'stressResults'],
    outputFields: ['metrics', 'overallHealth', 'actionItems'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §8.2' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-alco-dashboard',
    dependsOn: ['M-45'],
  },
  {
    moduleId: 'M-49',
    name: 'Excel Export with Data Gaps',
    nameEs: 'Exportación Excel con Brechas de Datos',
    category: C.REGULATORY_REPORTING,
    description: 'Multi-sheet Excel workbook with data gap manifest as Sheet 0',
    descriptionEs:
      'Libro Excel multi-hoja con manifiesto de brechas de datos como Hoja 0',
    serviceFile: 'alm/excel-export.service.ts',
    entryFunction: 'generateExcelReport',
    requiredInputs: ['almSummary', 'cossecCompliance', 'stressResults', 'gaps'],
    outputFields: ['xlsxBuffer', 'sheetCount', 'gapCount'],
    regulatoryReferences: [],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-excel-export',
    dependsOn: ['M-45'],
  },
  {
    moduleId: 'M-50',
    name: 'Regulatory Alert Pipeline',
    nameEs: 'Pipeline de Alertas Regulatorias',
    category: C.REGULATORY_REPORTING,
    description:
      'Automated regulatory publication monitoring and impact assessment',
    descriptionEs:
      'Monitoreo automatizado de publicaciones regulatorias y evaluación de impacto',
    serviceFile: 'ai/regulatory/regulatory-alert.service.ts',
    entryFunction: 'processRegulatoryAlerts',
    requiredInputs: ['regulatoryPublications'],
    outputFields: ['alerts', 'impactAssessments', 'actionItems'],
    regulatoryReferences: [],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-regulatory-alerts',
    dependsOn: [],
  },
  {
    moduleId: 'M-51',
    name: 'Audit Log & Trail',
    nameEs: 'Registro y Pista de Auditoría',
    category: C.REGULATORY_REPORTING,
    description: '7-year immutable audit trail for all system actions',
    descriptionEs:
      'Pista de auditoría inmutable de 7 años para todas las acciones del sistema',
    serviceFile: 'audit/audit.service.ts',
    entryFunction: 'writeAuditLog',
    requiredInputs: ['action', 'resource', 'actor', 'changes'],
    outputFields: ['auditLogId', 'timestamp'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Ley 255-2002 Art. 22' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-audit-trail',
    dependsOn: [],
  },
  {
    moduleId: 'M-52',
    name: 'Report Artifact Immutability',
    nameEs: 'Inmutabilidad de Artefactos de Informe',
    category: C.REGULATORY_REPORTING,
    description: 'SHA-256 checksummed, model-lineage-stamped report artifacts',
    descriptionEs:
      'Artefactos de informe con checksum SHA-256 y sello de linaje de modelos',
    serviceFile: 'alm/reports/reports.service.ts',
    entryFunction: 'generateAndRecordArtifact',
    requiredInputs: ['reportContent', 'preflightResult'],
    outputFields: ['artifactId', 'checksum', 'modelLineage'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §9' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-report-artifact',
    dependsOn: ['M-47'],
  },

  // ═══════════════════════════════════════════════════════════════
  // GOVERNANCE & ANALYTICS (M-53 through M-62)
  // ═══════════════════════════════════════════════════════════════
  {
    moduleId: 'M-53',
    name: 'CAMEL Composite Score',
    nameEs: 'Puntuación Compuesta CAMEL',
    category: C.GOVERNANCE,
    description: 'Capital-Asset-Management-Earnings-Liquidity composite rating',
    descriptionEs:
      'Calificación compuesta Capital-Activos-Administración-Ganancias-Liquidez',
    serviceFile: 'alm/exam-prep/camel-scorer.service.ts',
    entryFunction: 'calculateCAMELScore',
    requiredInputs: [
      'capitalMetrics',
      'assetQuality',
      'managementAssessment',
      'earnings',
      'liquidity',
    ],
    outputFields: ['compositeScore', 'componentScores', 'rating'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Examen de Supervisión COSSEC §12' },
      { body: R.NCUA, citation: 'NCUA CAMEL Rating System' },
    ],
    thresholds: [
      {
        metric: 'compositeScore',
        pass: '1–2',
        warn: '3',
        fail: '4–5',
        unit: 'rating',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-camel-scorer',
    dependsOn: ['M-21', 'M-33', 'M-28', 'M-11'],
  },
  {
    moduleId: 'M-54',
    name: 'CAMEL Certification',
    nameEs: 'Certificación CAMEL',
    category: C.GOVERNANCE,
    description:
      'Official bilingual CAMEL certification with examiner attestation',
    descriptionEs:
      'Certificación CAMEL bilingüe oficial con atestación de examinador',
    serviceFile: 'alm/exam-prep/camel-certification.service.ts',
    entryFunction: 'certify',
    requiredInputs: ['institutionId', 'period', 'camelScore'],
    outputFields: ['certificationId', 'period', 'compositeScore', 'pdf'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Examen de Supervisión COSSEC §12.5' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-camel-certification',
    dependsOn: ['M-53'],
  },
  {
    moduleId: 'M-55',
    name: 'Exam Readiness Assessment',
    nameEs: 'Evaluación de Preparación para Examen',
    category: C.GOVERNANCE,
    description:
      '12-category weighted COSSEC exam readiness scoring with remediation',
    descriptionEs:
      'Puntuación ponderada de preparación para examen COSSEC en 12 categorías con remediación',
    serviceFile: 'exam-prep/exam-prep-scoring.service.ts',
    entryFunction: 'assessExamReadiness',
    requiredInputs: ['institutionMetrics', 'policyDocumentation'],
    outputFields: ['overallGrade', 'categoryScores', 'remediationPlan'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Manual de Examen COSSEC' },
    ],
    thresholds: [
      {
        metric: 'overallGrade',
        pass: 'A–B',
        warn: 'C',
        fail: 'D–F',
        unit: 'grade',
      },
    ],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-exam-readiness',
    dependsOn: ['M-53'],
  },
  {
    moduleId: 'M-56',
    name: 'Peer Benchmarking',
    nameEs: 'Benchmarking de Pares',
    category: C.PEER_ANALYTICS,
    description: 'Quartile ranking against PR cooperativa peer group',
    descriptionEs:
      'Ranking por cuartiles contra grupo de pares de cooperativas PR',
    serviceFile: 'alm/peer-analytics.service.ts',
    entryFunction: 'calculatePeerRanking',
    requiredInputs: ['institutionMetrics', 'peerGroupData'],
    outputFields: ['quartileRank', 'percentile', 'peerComparison'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Carta Circular OC-2019-01 §10' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-peer-benchmarking',
    dependsOn: [],
  },
  {
    moduleId: 'M-57',
    name: 'Governed Scenario Library',
    nameEs: 'Biblioteca de Escenarios Gobernados',
    category: C.GOVERNANCE,
    description:
      'Centralized, versioned scenario library with approval workflow',
    descriptionEs:
      'Biblioteca centralizada y versionada de escenarios con flujo de aprobación',
    serviceFile: 'governance/governed-scenario.service.ts',
    entryFunction: 'getApprovedScenarios',
    requiredInputs: [],
    outputFields: ['scenarios', 'approvalStatus'],
    regulatoryReferences: [{ body: R.FRB, citation: 'SR 11-7 §VI' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-governed-scenarios',
    dependsOn: [],
  },
  {
    moduleId: 'M-58',
    name: 'Governed Benchmark Datasets',
    nameEs: 'Conjuntos de Datos de Referencia Gobernados',
    category: C.GOVERNANCE,
    description:
      'Checksummed benchmark datasets with refresh policy and provenance',
    descriptionEs:
      'Conjuntos de datos de referencia con checksum, política de actualización y procedencia',
    serviceFile: 'governance/governed-benchmark.service.ts',
    entryFunction: 'getApprovedBenchmarks',
    requiredInputs: [],
    outputFields: ['benchmarks', 'freshness', 'checksum'],
    regulatoryReferences: [{ body: R.FRB, citation: 'SR 11-7 §VII' }],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-governed-benchmarks',
    dependsOn: [],
  },
  {
    moduleId: 'M-59',
    name: 'Model Registry & Governance',
    nameEs: 'Registro y Gobernanza de Modelos',
    category: C.GOVERNANCE,
    description:
      '44-model production registry with lifecycle, validation artifacts, and lineage',
    descriptionEs:
      'Registro de producción de 44 modelos con ciclo de vida, artefactos de validación y linaje',
    serviceFile: 'model-registry/model-registry.service.ts',
    entryFunction: 'getApprovedModels',
    requiredInputs: [],
    outputFields: ['models', 'validationArtifacts', 'lineage'],
    regulatoryReferences: [
      { body: R.FRB, citation: 'SR 11-7' },
      { body: R.OCC, citation: 'OCC 2011-12' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-model-registry',
    dependsOn: [],
  },
  {
    moduleId: 'M-60',
    name: 'ROI Calculator',
    nameEs: 'Calculadora de ROI',
    category: C.PRICING,
    description:
      'Total cost of ownership and ROI calculation for prospect institutions',
    descriptionEs:
      'Costo total de propiedad y cálculo de ROI para instituciones prospecto',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'calculateROI',
    requiredInputs: ['institutionSize', 'currentCosts', 'pricingTier'],
    outputFields: ['annualSavings', 'roiPercent', 'paybackMonths'],
    regulatoryReferences: [],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-roi-calculator',
    dependsOn: [],
  },
  {
    moduleId: 'M-61',
    name: 'Data Export (CSV/JSON)',
    nameEs: 'Exportación de Datos (CSV/JSON)',
    category: C.REGULATORY_REPORTING,
    description: 'Raw data export for external analysis tools',
    descriptionEs:
      'Exportación de datos crudos para herramientas de análisis externo',
    serviceFile: 'alm/data-export.service.ts',
    entryFunction: 'exportData',
    requiredInputs: ['analysisRunId', 'format'],
    outputFields: ['csvBuffer', 'jsonPayload'],
    regulatoryReferences: [],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-data-export',
    dependsOn: [],
  },
  {
    moduleId: 'M-62',
    name: 'COSSEC Ratio Summary (12 Ratios)',
    nameEs: 'Resumen de Razones COSSEC (12 Razones)',
    category: C.REGULATORY_REPORTING,
    description: 'Consolidated view of all 12 COSSEC-required financial ratios',
    descriptionEs:
      'Vista consolidada de las 12 razones financieras requeridas por COSSEC',
    serviceFile: 'alm/alm-enterprise.service.ts',
    entryFunction: 'getCOSSECRatioSummary',
    requiredInputs: ['balanceSheetItems', 'incomeStatement'],
    outputFields: ['ratios', 'complianceStatus', 'trendIndicators'],
    regulatoryReferences: [
      { body: R.COSSEC, citation: 'Ley 255-2002 Art. 14, 15, 16' },
    ],
    thresholds: [],
    status: S.VALIDATED,
    modelRegistryKey: 'alm-cossec-ratio-summary',
    dependsOn: ['M-45'],
  },
];
