-- Member 360: canonical product code + per-loan lifecycle on member accounts.
--
-- WHAT THIS ADDS
-- --------------
--   * product_code       — canonical CooperativaProductCode resolved from the
--                          free-text product_type by mapProductLabel(). This is
--                          what lets a member's auto loan reach its own PD/LGD
--                          in product-registry.ts. NULLABLE: an unmappable
--                          label stays null and is disclosed as
--                          PRODUCT_TYPE_UNMAPPED rather than being bucketed
--                          into a default product it was never measured as.
--   * loan_stage         — the LOAN's own lifecycle stage, distinct from the
--                          member's. NULLABLE for non-loan accounts and for
--                          loans whose delinquency is unknown (D1: an
--                          unclassified loan must not render as CURRENT).
--   * original_principal — enables amortization progress. Nullable.
--   * external_loan_id   — join key back to loan_records.external_loan_id so an
--                          ingested member book reconciles against its tape.
--   * restructured /     — explicit lifecycle facts, never inferred from
--     charged_off          delinquency days. Both default false.
--
-- WHY THE ENUM TYPES ARE CREATED HERE, EXPLICITLY
-- -----------------------------------------------
-- The 2026-08-12 Member 360 migration declared enum-typed columns in
-- schema.prisma but created them as plain TEXT in SQL. Prisma Client is
-- generated from the datamodel, so every write it emitted cast to
-- `public."MemberLifecycleStage"` — a type that did not exist — and the
-- feature could not persist a single row. `prisma validate` and
-- `migrate deploy`/`status` both reported healthy against that database,
-- because neither checks whether a migration's SQL matches the datamodel.
--
-- This migration is generated by `prisma migrate diff --from-schema
-- <previous> --to-schema <current> --script`, so the CREATE TYPE statements
-- come from the datamodel itself rather than being hand-written and
-- forgotten. Verified by round-tripping: applying this file and re-running
-- migrate diff against the schema yields an empty diff.
--
-- SAFETY AGAINST LIVE DATA
-- ------------------------
-- Every statement is additive. New columns are either NULLABLE or carry a
-- DEFAULT, so existing member_accounts rows remain valid without a backfill,
-- and no existing column is altered, renamed or dropped.

-- CreateEnum
CREATE TYPE "CooperativaProductCode" AS ENUM ('PRESTAMO_PERSONAL', 'PRESTAMO_AUTO', 'HIPOTECA', 'PRESTAMO_COMERCIAL', 'PRESTAMO_GARANTIA_ACCIONES', 'CLUB_NAVIDAD', 'CUENTA_AHORRO', 'CERTIFICADO_DEPOSITO');

-- CreateEnum
CREATE TYPE "LoanLifecycleStage" AS ENUM ('ORIGINATED', 'CURRENT', 'EARLY_DELINQUENCY', 'DELINQUENT_30', 'DELINQUENT_60', 'NONACCRUAL', 'WORKOUT', 'PAID_OFF', 'CHARGED_OFF');

-- AlterTable
ALTER TABLE "member_accounts" ADD COLUMN     "charged_off" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "external_loan_id" TEXT,
ADD COLUMN     "loan_stage" "LoanLifecycleStage",
ADD COLUMN     "original_principal" DECIMAL(18,2),
ADD COLUMN     "product_code" "CooperativaProductCode",
ADD COLUMN     "restructured" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE INDEX "member_accounts_institution_id_product_code_idx" ON "member_accounts"("institution_id", "product_code");

-- CreateIndex
CREATE INDEX "member_accounts_institution_id_loan_stage_idx" ON "member_accounts"("institution_id", "loan_stage");

-- CreateIndex
CREATE INDEX "member_accounts_institution_id_external_loan_id_idx" ON "member_accounts"("institution_id", "external_loan_id");
