/**
 * Deterministic fixtures for agent UI development + test isolation.
 *
 * Activated via `?demo=1` query param on Decision Panel, Agent Activity,
 * and Copilot pages. Also used by vitest for snapshot-free assertion tests.
 *
 * Numbers are realistic PR cooperativa ranges (LCR ~112%, NIM ~3.52%,
 * NII impact $1–4M, COSSEC Carta Circular refs, CAMEL 2–3).
 */

import type {
  AgentAlertRecord,
  AgentAuditStep,
  AgentRun,
  ALMDecisionOutput,
  CFOCopilotOutput,
  RiskMonitorOutput,
} from '@/types/agents';

// ─── ALM Decision ───────────────────────────────────────────────────────────

export const FIXTURE_ALM_DECISION: ALMDecisionOutput = {
  agentId: 'alm_decision',
  version: '2.0',
  runId: 'fix-alm-001',
  institutionId: 'fix-inst-001',
  timestamp: '2026-04-15T14:32:00.000Z',
  language: 'bilingual',
  healthSnapshot: {
    overall: 64,
    capital: 78,
    liquidity: 58,
    rateRisk: 52,
    credit: 71,
    concentration: 66,
    label: 'FAIR',
    trend: 'deteriorating',
  },
  topRisks: [
    {
      rank: 1,
      domain: 'Interest Rate Risk',
      priorityScore: 24,
      severity: 'HIGH',
      finding:
        'NII at +200bps declines 6.2% ($2.1M). Duration gap of −1.8yr driven by 3yr fixed-rate auto loan concentration. Exceeds IRR policy limit of 5.5%.',
      findingEs:
        'NII a +200bps disminuye 6.2% ($2.1M). Brecha de duración de −1.8yr impulsada por concentración de préstamos de auto a tasa fija de 3 años. Excede el límite de política IRR de 5.5%.',
      dollarImpact: 2_100_000,
      dollarImpactPct: 6.2,
      regulatoryRef: 'COSSEC Carta Circular 2021-02 §III.B',
      toolsUsed: ['runFullSwarm', 'runRateShock', 'getRepricingGap'],
    },
    {
      rank: 2,
      domain: 'Liquidity Risk',
      priorityScore: 20,
      severity: 'HIGH',
      finding:
        'LCR at 112% — 3pp above minimum but trending down (was 119% prior quarter). NSFR adequate at 108%. Stress survival horizon: 28 days.',
      findingEs:
        'LCR en 112% — 3pp sobre el mínimo pero con tendencia a la baja (era 119% trimestre anterior). NSFR adecuado en 108%. Horizonte de supervivencia en estrés: 28 días.',
      dollarImpact: 850_000,
      dollarImpactPct: 2.5,
      regulatoryRef: 'COSSEC Reg. 8866 §7.2',
      toolsUsed: ['runFullSwarm', 'getLCR', 'getNSFR'],
    },
    {
      rank: 3,
      domain: 'Concentration Risk',
      priorityScore: 15,
      severity: 'MEDIUM',
      finding:
        'Auto loan sector HHI: 2,840 (high). 34% of total portfolio in a single sector. Top-member exposure at 8.2% of net worth.',
      findingEs:
        'HHI del sector de préstamos de auto: 2,840 (alto). 34% de cartera total en un solo sector. Exposición de socio principal al 8.2% del patrimonio neto.',
      dollarImpact: 640_000,
      dollarImpactPct: 1.9,
      regulatoryRef: 'COSSEC Carta Circular 2019-01 §IV',
      toolsUsed: ['runFullSwarm', 'getConcentration'],
    },
    {
      rank: 4,
      domain: 'Credit Risk',
      priorityScore: 12,
      severity: 'MEDIUM',
      finding:
        'CECL allowance coverage ratio: 1.42% vs peer median 1.58%. Under-reserved by $380K in commercial real estate segment.',
      findingEs:
        'Ratio de cobertura CECL: 1.42% vs mediana de pares 1.58%. Sub-reservado por $380K en segmento de bienes raíces comerciales.',
      dollarImpact: 380_000,
      dollarImpactPct: 1.1,
      regulatoryRef: 'ASC 326-20',
      toolsUsed: ['runFullSwarm', 'getCECL', 'getPeerBenchmark'],
    },
    {
      rank: 5,
      domain: 'Capital Adequacy',
      priorityScore: 8,
      severity: 'LOW',
      finding:
        'Net worth ratio: 7.4% (well-capitalized threshold: 7.0%). Adequate but declining 20bps QoQ. Risk-based capital ratio: 12.1%.',
      findingEs:
        'Razón de patrimonio neto: 7.4% (umbral bien capitalizado: 7.0%). Adecuado pero en declive 20bps QoQ. Ratio de capital basado en riesgo: 12.1%.',
      dollarImpact: 210_000,
      dollarImpactPct: 0.6,
      regulatoryRef: 'NCUA §702.102',
      toolsUsed: ['runFullSwarm', 'getCapitalAdequacy'],
    },
  ],
  decisionQueue: [
    {
      priority: 1,
      action:
        'Shift $15M from 5yr fixed auto loans to 1yr variable structures to reduce duration gap to −0.3yr.',
      actionEs:
        'Mover $15M de préstamos de auto fijos a 5 años a estructuras variables a 1 año para reducir la brecha de duración a −0.3yr.',
      expectedImpact: '+12bps NIM improvement (+$840K annualized)',
      deadline: '60d',
      owner: 'CFO',
      regulatoryRef: 'COSSEC Carta Circular 2021-02',
      status: 'PENDING',
    },
    {
      priority: 2,
      action:
        'Increase HQLA buffer by $2M through Treasury bill ladder (4-week/8-week/13-week).',
      actionEs:
        'Aumentar buffer HQLA en $2M mediante escalera de letras del Tesoro (4/8/13 semanas).',
      expectedImpact: 'LCR improvement to 121% (+9pp)',
      deadline: '30d',
      owner: 'CFO',
      regulatoryRef: 'COSSEC Reg. 8866',
      status: 'PENDING',
    },
    {
      priority: 3,
      action:
        'Cap auto loan originations at 30% of total portfolio until HHI < 2,500.',
      actionEs:
        'Limitar originaciones de préstamos de auto al 30% de cartera total hasta HHI < 2,500.',
      expectedImpact: 'HHI reduction to ~2,400 over 90 days',
      deadline: '90d',
      owner: 'ALM_COMMITTEE',
      regulatoryRef: 'COSSEC Carta Circular 2019-01',
      status: 'PENDING',
    },
    {
      priority: 4,
      action:
        'Increase CECL reserve by $380K in CRE segment to match peer median 1.58%.',
      actionEs:
        'Aumentar reserva CECL en $380K en segmento CRE para igualar mediana de pares 1.58%.',
      expectedImpact: 'Coverage ratio to peer median',
      deadline: '30d',
      owner: 'CFO',
      regulatoryRef: 'ASC 326-20',
      status: 'PENDING',
    },
    {
      priority: 5,
      action:
        'Review capital plan stress scenarios with 25bps buffer added to net worth floor.',
      actionEs:
        'Revisar escenarios de estrés del plan de capital con buffer de 25bps añadido al piso de patrimonio neto.',
      expectedImpact: 'Maintain well-capitalized status through cycle',
      deadline: '60d',
      owner: 'BOARD',
      regulatoryRef: 'NCUA §702.102',
      status: 'PENDING',
    },
  ],
  brief:
    'This institution faces elevated interest rate risk as the primary concern. NII sensitivity at +200bps exceeds policy limits by 70bps, driven by a duration mismatch from concentrated fixed-rate auto lending. Liquidity is trending down despite adequate LCR. The decision queue prioritizes rate risk restructuring first ($840K annual benefit), followed by HQLA buffer build and concentration caps. Credit reserves need a $380K top-up in CRE. Capital is adequate but thin — 40bps above the well-capitalized threshold with a negative trend.',
  briefEs:
    'Esta institución enfrenta un riesgo de tasa de interés elevado como preocupación principal. La sensibilidad de NII a +200bps excede los límites de política por 70bps, impulsada por un desfase de duración de préstamos de auto a tasa fija. La liquidez tiende a la baja a pesar de un LCR adecuado. La cola de decisiones prioriza la reestructuración del riesgo de tasa primero (beneficio anual de $840K), seguido por la construcción del buffer HQLA y topes de concentración. Las reservas de crédito necesitan un aumento de $380K en CRE. El capital es adecuado pero delgado — 40bps sobre el umbral de bien capitalizado con tendencia negativa.',
  auditTraceId: 'fix-trace-001',
};

// ─── Risk Monitor ───────────────────────────────────────────────────────────

export const FIXTURE_RISK_MONITOR: RiskMonitorOutput = {
  agentId: 'risk_monitor',
  runId: 'fix-rm-001',
  institutionId: 'fix-inst-001',
  scanKind: 'daily',
  alertCount: 3,
  quietRun: false,
  alerts: [
    {
      category: 'liquidity',
      severity: 'CRITICAL',
      metric: 'LCR',
      currentValue: 112,
      threshold: 115,
      delta: -3,
      trend: 'worsening',
      finding:
        'LCR dropped below internal policy limit of 115%. Regulatory minimum 100% still met but trajectory is negative.',
      findingEs:
        'LCR cayó por debajo del límite de política interna de 115%. El mínimo regulatorio de 100% aún se cumple pero la trayectoria es negativa.',
      recommendation: 'Execute HQLA buffer increase per decision queue item #2.',
      regulatoryRef: 'COSSEC Reg. 8866 §7.2',
      deadline: '2026-05-15',
      dedupSeed: 'lcr-below-policy-115',
    },
    {
      category: 'rate_risk',
      severity: 'HIGH',
      metric: 'NII Sensitivity +200bps',
      currentValue: 6.2,
      threshold: 5.5,
      delta: -0.7,
      trend: 'worsening',
      finding:
        'NII sensitivity at +200bps is 6.2%, exceeding the 5.5% policy limit by 70bps.',
      findingEs:
        'La sensibilidad NII a +200bps es 6.2%, excediendo el límite de política de 5.5% por 70bps.',
      recommendation:
        'Restructure $15M from fixed to variable per decision queue item #1.',
      regulatoryRef: 'COSSEC Carta Circular 2021-02 §III.B',
      deadline: '2026-06-15',
      dedupSeed: 'nii-sensitivity-200bps-breach',
    },
    {
      category: 'concentration',
      severity: 'MEDIUM',
      metric: 'Auto Loan HHI',
      currentValue: 2840,
      threshold: 2500,
      delta: -340,
      trend: 'stable',
      finding:
        'Auto loan sector HHI remains above 2,500 threshold. No improvement since last scan.',
      findingEs:
        'HHI del sector de préstamos de auto permanece sobre el umbral de 2,500. Sin mejora desde el último escaneo.',
      recommendation: 'Enforce 30% cap per decision queue item #3.',
      regulatoryRef: 'COSSEC Carta Circular 2019-01 §IV',
      deadline: '2026-07-15',
      dedupSeed: 'auto-hhi-above-2500',
    },
  ],
};

// ─── Agent Alert Records (persisted) ────────────────────────────────────────

export const FIXTURE_ALERTS: AgentAlertRecord[] =
  FIXTURE_RISK_MONITOR.alerts.map((a, i) => ({
    id: `fix-alert-${String(i + 1).padStart(3, '0')}`,
    runId: FIXTURE_RISK_MONITOR.runId,
    institutionId: FIXTURE_RISK_MONITOR.institutionId,
    category: a.category,
    severity: a.severity,
    status: i === 0 ? 'OPEN' : i === 1 ? 'ACKNOWLEDGED' : 'OPEN',
    metric: a.metric,
    currentValue: a.currentValue,
    threshold: a.threshold,
    delta: a.delta,
    finding: a.finding,
    findingEs: a.findingEs,
    recommendation: a.recommendation,
    regulatoryRef: a.regulatoryRef,
    deadline: a.deadline,
    dedupKey: `sha256-${a.dedupSeed}-fix-inst-001`,
    occurrenceCount: i === 0 ? 3 : 1,
    notifiedAt: i === 0 ? '2026-04-15T14:35:00.000Z' : null,
    acknowledgedAt: i === 1 ? '2026-04-15T15:10:00.000Z' : null,
    acknowledgedBy: i === 1 ? 'fix-user-cfo' : null,
    resolutionNote: null,
    createdAt: '2026-04-15T14:33:00.000Z',
  }));

// ─── CFO Copilot Turns ──────────────────────────────────────────────────────

export const FIXTURE_COPILOT_TURNS: CFOCopilotOutput[] = [
  {
    agentId: 'cfo_copilot',
    runId: 'fix-copilot-001',
    institutionId: 'fix-inst-001',
    sessionId: 'fix-session-001',
    language: 'en',
    message:
      'At +200bps, your NII drops 6.2% ($2.1M). The primary driver is a −1.8yr duration gap from your 3yr fixed-rate auto loan book. Shifting $15M to variable-rate structures closes the gap to −0.3yr and reduces NII sensitivity to 4.1%. This adds +12bps to NIM ($840K annualized). The timeline is 60 days through natural runoff and new origination guidelines.',
    followups: [
      {
        en: 'What happens if I only shift $10M instead of $15M?',
        es: '¿Qué pasa si solo muevo $10M en lugar de $15M?',
      },
      {
        en: 'Show me the repricing gap by maturity bucket.',
        es: 'Muéstrame la brecha de repreciación por cubo de vencimiento.',
      },
      {
        en: 'How does our rate risk compare to peer institutions?',
        es: '¿Cómo se compara nuestro riesgo de tasa con instituciones pares?',
      },
      {
        en: 'Run a Monte Carlo simulation on NII at ±300bps.',
        es: 'Ejecuta una simulación Monte Carlo sobre NII a ±300bps.',
      },
    ],
    toolsCalled: ['runRateShock', 'getRepricingGap', 'getDepositBeta'],
  },
  {
    agentId: 'cfo_copilot',
    runId: 'fix-copilot-002',
    institutionId: 'fix-inst-001',
    sessionId: 'fix-session-001',
    language: 'en',
    message:
      'At $10M shifted (vs recommended $15M), duration gap closes to −0.8yr instead of −0.3yr. NII sensitivity drops to 5.0% — still below your 5.5% policy limit, but only 50bps of headroom. A 50bps parallel shift beyond your shock scenario would breach policy. Recommendation: shift $15M for a comfortable 140bps buffer. If capital constraints limit the shift, $12M achieves −0.5yr gap and 4.6% sensitivity — a reasonable compromise.',
    followups: [
      {
        en: 'What are the capital constraints on the full $15M shift?',
        es: '¿Cuáles son las restricciones de capital para el cambio completo de $15M?',
      },
      {
        en: 'Show me the impact on FTP by product line.',
        es: 'Muéstrame el impacto en FTP por línea de producto.',
      },
      {
        en: 'Generate a committee report with this scenario analysis.',
        es: 'Genera un informe de comité con este análisis de escenario.',
      },
      {
        en: 'What does COSSEC guidance say about the 5.5% limit?',
        es: '¿Qué dice la guía de COSSEC sobre el límite de 5.5%?',
      },
    ],
    toolsCalled: ['runRateShock', 'runMonteCarlo'],
  },
  {
    agentId: 'cfo_copilot',
    runId: 'fix-copilot-003',
    institutionId: 'fix-inst-001',
    sessionId: 'fix-session-001',
    language: 'es',
    message:
      'Resultados Monte Carlo a ±300bps (10,000 iteraciones): NII medio −8.4% ($2.9M) en escenario +300bps, con intervalo de confianza 95% de [−10.1%, −6.8%]. En escenario −300bps, NII medio +3.2% ($1.1M). La asimetría refleja su posición de duración larga. La cola del 5% (peor escenario) muestra NII −10.1% ($3.5M) — este es el número que debe presentar al comité como escenario adverso.',
    followups: [
      {
        en: 'Export this analysis as a board presentation.',
        es: 'Exporta este análisis como presentación para la junta.',
      },
      {
        en: 'How does this compare to our peers at ±300bps?',
        es: '¿Cómo se compara esto con nuestros pares a ±300bps?',
      },
      {
        en: 'What hedging strategies could limit the tail risk?',
        es: '¿Qué estrategias de cobertura podrían limitar el riesgo de cola?',
      },
      {
        en: 'Show the detailed Monte Carlo distribution chart.',
        es: 'Muestra el gráfico detallado de distribución Monte Carlo.',
      },
    ],
    toolsCalled: ['runMonteCarlo', 'runRateShock', 'getPeerBenchmark'],
  },
];

// ─── Agent Runs ─────────────────────────────────────────────────────────────

export const FIXTURE_RUNS: AgentRun[] = [
  {
    id: 'fix-alm-001',
    agentId: 'ALM_DECISION',
    agentVersion: '1.0.0',
    promptVersion: '1.0.0',
    institutionId: 'fix-inst-001',
    organizationId: 'fix-org-001',
    triggeredByUserId: 'fix-user-cfo',
    triggerKind: 'UPLOAD',
    triggerRef: 'balance-sheet-2026-q1.csv',
    idempotencyKey: 'fix-idempotency-001',
    input: { balanceSheetId: 'fix-bs-001' },
    output: FIXTURE_ALM_DECISION,
    status: 'SUCCEEDED',
    startedAt: '2026-04-15T14:30:00.000Z',
    completedAt: '2026-04-15T14:30:38.000Z',
    durationMs: 38_000,
    toolCallCount: 8,
    llmTurnCount: 3,
    inputTokens: 4200,
    outputTokens: 1800,
    costUsdCents: 42,
    auditRootHash: 'sha256-fix-root-001',
    errorCode: null,
    errorMessage: null,
    createdAt: '2026-04-15T14:30:00.000Z',
  },
  {
    id: 'fix-rm-001',
    agentId: 'RISK_MONITOR',
    agentVersion: '1.0.0',
    promptVersion: '1.0.0',
    institutionId: 'fix-inst-001',
    organizationId: 'fix-org-001',
    triggeredByUserId: null,
    triggerKind: 'SCHEDULE',
    triggerRef: 'daily-9am-risk-scan',
    idempotencyKey: 'fix-idempotency-002',
    input: {},
    output: FIXTURE_RISK_MONITOR,
    status: 'SUCCEEDED',
    startedAt: '2026-04-15T13:00:00.000Z',
    completedAt: '2026-04-15T13:00:06.000Z',
    durationMs: 6_000,
    toolCallCount: 5,
    llmTurnCount: 2,
    inputTokens: 2800,
    outputTokens: 900,
    costUsdCents: 18,
    auditRootHash: 'sha256-fix-root-002',
    errorCode: null,
    errorMessage: null,
    createdAt: '2026-04-15T13:00:00.000Z',
  },
  {
    id: 'fix-copilot-001',
    agentId: 'CFO_COPILOT',
    agentVersion: '1.0.0',
    promptVersion: '1.0.0',
    institutionId: 'fix-inst-001',
    organizationId: 'fix-org-001',
    triggeredByUserId: 'fix-user-cfo',
    triggerKind: 'USER_QUERY',
    triggerRef: null,
    idempotencyKey: 'fix-idempotency-003',
    input: { query: 'What happens if rates rise 200bps?' },
    output: FIXTURE_COPILOT_TURNS[0],
    status: 'SUCCEEDED',
    startedAt: '2026-04-15T14:32:00.000Z',
    completedAt: '2026-04-15T14:32:04.000Z',
    durationMs: 4_200,
    toolCallCount: 3,
    llmTurnCount: 1,
    inputTokens: 3100,
    outputTokens: 600,
    costUsdCents: 12,
    auditRootHash: 'sha256-fix-root-003',
    errorCode: null,
    errorMessage: null,
    createdAt: '2026-04-15T14:32:00.000Z',
  },
  {
    id: 'fix-running-001',
    agentId: 'STRESS_TESTING',
    agentVersion: '1.0.0',
    promptVersion: '1.0.0',
    institutionId: 'fix-inst-001',
    organizationId: 'fix-org-001',
    triggeredByUserId: 'fix-user-cfo',
    triggerKind: 'API',
    triggerRef: null,
    idempotencyKey: 'fix-idempotency-004',
    input: { scenarioIds: ['hurricane-pr', 'recession-2025'] },
    output: null,
    status: 'RUNNING',
    startedAt: '2026-04-15T14:45:00.000Z',
    completedAt: null,
    durationMs: null,
    toolCallCount: 2,
    llmTurnCount: 1,
    inputTokens: null,
    outputTokens: null,
    costUsdCents: null,
    auditRootHash: null,
    errorCode: null,
    errorMessage: null,
    createdAt: '2026-04-15T14:45:00.000Z',
  },
  {
    id: 'fix-failed-001',
    agentId: 'COMMITTEE_REPORT',
    agentVersion: '1.0.0',
    promptVersion: '1.0.0',
    institutionId: 'fix-inst-001',
    organizationId: 'fix-org-001',
    triggeredByUserId: 'fix-user-cfo',
    triggerKind: 'CHAIN',
    triggerRef: 'fix-alm-001',
    idempotencyKey: 'fix-idempotency-005',
    input: {
      sourceRunId: 'fix-alm-001',
      committeeType: 'board',
      language: 'bilingual',
    },
    output: null,
    status: 'FAILED',
    startedAt: '2026-04-15T14:31:00.000Z',
    completedAt: '2026-04-15T14:31:42.000Z',
    durationMs: 42_000,
    toolCallCount: 1,
    llmTurnCount: 1,
    inputTokens: 5200,
    outputTokens: 200,
    costUsdCents: 8,
    auditRootHash: 'sha256-fix-root-005',
    errorCode: 'LLM_CONTEXT_EXCEEDED',
    errorMessage: 'Context window exceeded during narrative generation',
    createdAt: '2026-04-15T14:31:00.000Z',
  },
];

// ─── Audit trace ────────────────────────────────────────────────────────────

export const FIXTURE_AUDIT_TRACE: AgentAuditStep[] = [
  {
    id: 'fix-step-001',
    runId: 'fix-alm-001',
    stepNumber: 1,
    stepKind: 'RUN_STARTED',
    toolName: null,
    toolInput: null,
    toolOutput: null,
    llmPrompt: null,
    llmOutput: null,
    durationMs: 2,
    createdAt: '2026-04-15T14:30:00.001Z',
    contentHash: 'sha256-step-001',
    prevHash: null,
  },
  {
    id: 'fix-step-002',
    runId: 'fix-alm-001',
    stepNumber: 2,
    stepKind: 'TOOL_CALL',
    toolName: 'runFullSwarm',
    toolInput: { institutionId: 'fix-inst-001' },
    toolOutput: null,
    llmPrompt: null,
    llmOutput: null,
    durationMs: 12_400,
    createdAt: '2026-04-15T14:30:00.100Z',
    contentHash: 'sha256-step-002',
    prevHash: 'sha256-step-001',
  },
  {
    id: 'fix-step-003',
    runId: 'fix-alm-001',
    stepNumber: 3,
    stepKind: 'TOOL_RESULT',
    toolName: 'runFullSwarm',
    toolInput: null,
    toolOutput: {
      completedModels: [
        'rateShock',
        'liquidity',
        'cecl',
        'concentration',
        'ftp',
        'peers',
        'camel',
        'climate',
        'earlyWarning',
        'capitalAdequacy',
        'repricingGap',
        'depositBeta',
      ],
      failedModels: [],
      confidence: { score: 100, label: 'HIGH', missingCritical: [] },
    },
    llmPrompt: null,
    llmOutput: null,
    durationMs: 1,
    createdAt: '2026-04-15T14:30:12.500Z',
    contentHash: 'sha256-step-003',
    prevHash: 'sha256-step-002',
  },
  {
    id: 'fix-step-004',
    runId: 'fix-alm-001',
    stepNumber: 4,
    stepKind: 'LLM_TURN',
    toolName: null,
    toolInput: null,
    toolOutput: null,
    llmPrompt: '[system prompt + context — 4,200 tokens]',
    llmOutput: '[structured reasoning — identified 5 risks, generated brief]',
    durationMs: 18_200,
    createdAt: '2026-04-15T14:30:12.600Z',
    contentHash: 'sha256-step-004',
    prevHash: 'sha256-step-003',
  },
  {
    id: 'fix-step-005',
    runId: 'fix-alm-001',
    stepNumber: 5,
    stepKind: 'TOOL_CALL',
    toolName: 'runRateShock',
    toolInput: { institutionId: 'fix-inst-001', shockBps: [100, 200, 300, -100, -200] },
    toolOutput: null,
    llmPrompt: null,
    llmOutput: null,
    durationMs: 3_100,
    createdAt: '2026-04-15T14:30:30.800Z',
    contentHash: 'sha256-step-005',
    prevHash: 'sha256-step-004',
  },
  {
    id: 'fix-step-006',
    runId: 'fix-alm-001',
    stepNumber: 6,
    stepKind: 'CONTRACT_VALIDATION',
    toolName: null,
    toolInput: null,
    toolOutput: { valid: true, schemaVersion: '2.0' },
    llmPrompt: null,
    llmOutput: null,
    durationMs: 5,
    createdAt: '2026-04-15T14:30:37.500Z',
    contentHash: 'sha256-step-006',
    prevHash: 'sha256-step-005',
  },
  {
    id: 'fix-step-007',
    runId: 'fix-alm-001',
    stepNumber: 7,
    stepKind: 'RUN_COMPLETED',
    toolName: null,
    toolInput: null,
    toolOutput: { status: 'SUCCEEDED', durationMs: 38_000 },
    llmPrompt: null,
    llmOutput: null,
    durationMs: 1,
    createdAt: '2026-04-15T14:30:38.000Z',
    contentHash: 'sha256-step-007',
    prevHash: 'sha256-step-006',
  },
];
